### PR TITLE
fix(eap): Remove integer attribute values larger than I64::MAX

### LINKED ISSUE #5612: Validate u64 > i64::MAX for EAP item attributes
EAP only has a signed 64 bit type, the protocol also only allows i64, but Relay does parse `u64` correctly.

We need to make sure integers > i64::max are removed and a `meta` entry is left in place

### PR DESCRIPTION
**Pull request by elramen**
Remove integer attribute values larger than I64::MAX as EAP only supports signed 64 bit ints. Add an error along with the removed value to the attribute's metadata.

Fixes #5612

### CODE REVIEW

**Comment by Dav1dde** [comment]
As discussed, next steps to add an integration test and verify code behaves as desired.

**Review by jjbayer — APPROVED** [review]

File: relay-event-normalization/src/eap/mod.rs [hunk 1]
```diff
@@ -123,7 +123,13 @@ pub fn normalize_attribute_types(attributes: &mut Annotated<Attributes>) {
         match (&mut inner.value.ty, &mut inner.value.value) {
             (Annotated(Some(Boolean), _), Annotated(Some(Value::Bool(_)), _)) => (),
             (Annotated(Some(Integer), _), Annotated(Some(Value::I64(_)), _)) => (),
-            (Annotated(Some(Integer), _), Annotated(Some(Value::U64(_)), _)) => (),
+            (Annotated(Some(Integer), _), Annotated(Some(Value::U64(u)), _)) => {
+                if *u > i64::MAX as u64 {
```
Comment (Dav1dde) [inline relay-event-normalization/src/eap/mod.rs]: I think I would write this as `i64::try_from(*u).is_ok()`

File: relay-event-normalization/src/eap/mod.rs [hunk 2]
```diff
@@ -123,7 +123,13 @@ pub fn normalize_attribute_types(attributes: &mut Annotated<Attributes>) {
         match (&mut inner.value.ty, &mut inner.value.value) {
             (Annotated(Some(Boolean), _), Annotated(Some(Value::Bool(_)), _)) => (),
             (Annotated(Some(Integer), _), Annotated(Some(Value::I64(_)), _)) => (),
-            (Annotated(Some(Integer), _), Annotated(Some(Value::U64(_)), _)) => (),
+            (Annotated(Some(Integer), _), Annotated(Some(Value::U64(u)), _)) => {
```
Comment (Dav1dde) [inline relay-event-normalization/src/eap/mod.rs]: Since the code in this branch is equivalent to the default error branch, you can also write this as:


```suggestion
            (Annotated(Some(Integer), _), Annotated(Some(Value::U64(u)), _))
                if i64::try_from(*u).is_ok() => {}
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -7,6 +7,7 @@
 - Emit outcomes for spans trimmed from a transaction. ([#5410](https://github.com/getsentry/relay/pull/5410))
 - Support `sample` alias in CSP reports. ([#5554](https://github.com/getsentry/relay/pull/5554))
 - Fix inconsistencies with Insights' expected attributes. ([#5561](https://github.com/getsentry/relay/pull/5561))
+- Remove EAP integer attributes larger than I64::MAX. ([#5621](https://github.com/getsentry/relay/pull/5621))
```
Comment (Dav1dde) [inline CHANGELOG.md]:
```suggestion
- Remove EAP integer attributes larger than `i64::MAX`. ([#5621](https://github.com/getsentry/relay/pull/5621))
```

Or maybe:

```suggestion
- Validate log/span/metric attribute integers to fit within an `i64`. ([#5621](https://github.com/getsentry/relay/pull/5621))
```

**Review by Dav1dde — APPROVED** [review]
Oops, meant to approve before, it's really just nits.

**Review by Dav1dde — APPROVED** [review]
