### PR TITLE
fix(store): Apply clock drift correction based on received_at

### LINKED ISSUE #534: Fragile clock drift correction
_From https://github.com/getsentry/relay/pull/526#discussion_r395376450_

@jan-auer wrote:

> @untitaker clock drift correction looks extremely fragile. It should use a timestamp of when the event was received, not when the processor runs (now). Since we can have arbitrary delays inside Relay due to project config fetching, this can massively skew the clock -- more than what's expected from usual clock skew. This means, the TransactionsProcessor should always receive sent_at and also received_at instead of now.
>
> Also, doing clock drift correction with the end timestamp probably does more harm than it helps. We cannot assume that the transaction is sent immediately after it's complete (especially if we want to start batching up in the SDK).

### LINKED ISSUE #535: TransactionsProcessor modifies event timestamps by default
`TransactionsProcessor` modifies event timestamps by default as part of a "clock drift detection" feature.

Disabling it requires setting a value on the `now` field. None of this is documented.

The behavior is surprising, and makes constructing tests and generally using `TransactionsProcessor` unnecessarily hard, requiring deep knowledge on the implementation details.

### PR DESCRIPTION
**Pull request by jan-auer**
Moves clock drift correction into its own processor. The clock drift is now defined as `received_at - sent_at`, where the two components are defined as:

 - `sent_at`: The timestamp of the client at which the request was sent to the server. 
 - `received_at`: The timestamp when the request reached the Relay endpoint.

Both timestamps are propagated into the store normalizer, where they are applied by a new `ClockDriftProcessor`. The event's timestamp is no longer used, since event submission may be delayed. The minimum drift is 55 minutes; anything lower will skip clock drift correction.

Fixes https://github.com/getsentry/relay/issues/534
Fixes https://github.com/getsentry/relay/issues/535

### CODE REVIEW

File: relay-general/src/store/mod.rs [hunk 1]
```diff
@@ -31,6 +32,8 @@ pub struct StoreConfig {
     pub protocol_version: Option<String>,
     pub grouping_config: Option<Value>,
     pub user_agent: Option<String>,
+    pub received_at: Option<DateTime<Utc>>,
```
Comment (jan-auer) [inline relay-general/src/store/mod.rs:35]: This is only optional to retain `Default for StoreConfig`. Effectively, it is always set in the event processor. Internally, `StoreProcessor` defaults to `Utc::now` if we ever choose to not pass a value here.

File: relay-server/src/actors/events.rs [hunk 2]
```diff
@@ -519,6 +520,7 @@ impl EventProcessor {
             remove_other: Some(true),
             normalize_user_agent: Some(true),
             sent_at: envelope.sent_at(),
+            received_at: Some(relay_common::instant_to_date_time(start_time)),
```
Comment (jan-auer) [inline relay-server/src/actors/events.rs:523]: We convert from `Instant` to `DateTime` as close as possible to normalization to ensure we have an accurate clock.

**Review by HazAT — APPROVED** [review]
Logically LGTM I can't really judge the implementation.
The only thing I see is that the unit tests only test `event.timestamp`, `event.start_timestamp` and not breadcrumbs/spans. I suppose this is tested somewhere else.

**Comment by dashed** [comment]
@jan-auer What was the reason for choosing 55 minutes as the minimum threshold for deciding a clock drift occurred?

File: relay-general/src/store/clock_drift.rs [hunk 3]
```diff
@@ -0,0 +1,263 @@
+use std::fmt;
+
+use chrono::{DateTime, Duration as SignedDuration, Utc};
+
+use crate::processor::{ProcessValue, ProcessingState, Processor};
+use crate::protocol::Event;
+use crate::types::{Error, ErrorKind, Meta, ProcessingResult, Timestamp};
+
+/// The minimum clock drift for correction to apply.
```
Comment (untitaker) [inline relay-general/src/store/clock_drift.rs:9]: Would add the reasoning here or move the processor's docstring to the module-level

File: relay-common/Cargo.toml [hunk 4]
```diff
@@ -12,6 +12,7 @@ publish = false
 [dependencies]
 backoff = "0.1.5"
 cadence = "0.17.1"
+chrono = { version = "0.4.7", optional = true }
```
Comment (untitaker) [inline relay-common/Cargo.toml:15]: Why's chrono optional, isn't that feature used all the time anyway?

File: relay-general/src/store/clock_drift.rs [hunk 5]
```diff
@@ -0,0 +1,263 @@
...
+        _meta: &mut Meta,
+        state: &ProcessingState<'_>,
+    ) -> ProcessingResult {
+        event.process_child_values(self, state)?;
+
+        if let Some(correction) = self.correction {
+            let timestamp_meta = event.timestamp.meta_mut();
+            timestamp_meta.add_error(Error::with(ErrorKind::InvalidData, |e| {
+                let reason = format!(
+                    "clock drift: all timestamps adjusted by {}",
```
Comment (untitaker) [inline relay-general/src/store/clock_drift.rs:111]: Not a huge fan of producing error messages here, we might want to refactor _meta to emit reason *codes* (not related to this PR in particular, just for the future)

**Review by untitaker — APPROVED** [review]

File: relay-common/Cargo.toml (hunk 4 above)
Comment (jan-auer) [reply relay-common/Cargo.toml:15]: Didn't bother looking, but since it wasn't there and I only needed it in the `processing` feature, it was straight-forward.

File: relay-general/src/store/clock_drift.rs (hunk 5 above)
Comment (jan-auer) [reply relay-general/src/store/clock_drift.rs:111]: The `ErrorKind` you saw is such a reason code, but I didn't want to touch Sentry for this now. If you like, we can follow up with a new error kind and then teach Sentry about it.

**Comment by HazAT** [comment]
@dashed https://github.com/getsentry/relay/pull/580/files#diff-ad89addad454e6fa19b045a03bd12a1fR61-R63

File: relay-general/src/store/clock_drift.rs (hunk 3 above)
Comment (jan-auer) [reply relay-general/src/store/clock_drift.rs:9]: This is already on the doc-string `ClockDriftProcessor`, which will be exported in a later PR (so that it can be used by non-processing Relays). 

@dashed you can find the reasoning in that same docstring:

```
/// There is a minimum clock drift of _55 minutes_ to compensate for network latency and small clock
/// drift on the sender's machine, but allow to detect timezone differences. For differences lower
/// than that, no correction is performed.
```

Let me know if you'd like me to clarify.
