### PR TITLE
fix(processor): Remove form data envelope items

### LINKED ISSUE #3359: Form Data events are dropped
Form Data events are dropped in the store.

https://github.com/getsentry/relay/blob/3bd026610b483e3c1120238b7e1aa5dd0feecc4d/relay-server/src/services/store.rs#L283-L302

[S4S Issue](https://sentry.my.sentry.io/organizations/sentry/issues/729445/)

### PR DESCRIPTION
**Pull request by iambriccardo**
This PR removes form data envelope items whenever a standalone envelope is processed. This fixes an issue where we were attempting to write form data items to Kafka, which are not supported.

Closes: https://github.com/getsentry/relay/issues/3359

### CODE REVIEW

File: relay-server/src/services/processor/standalone.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+use crate::utils::TypedEnvelope;
+
+/// Processes a standalone envelope by removing unnecessary items.
+///
+/// This function removes form data items from the envelope since they are not needed for
+/// standalone processing.
+pub fn process(managed_envelope: &mut TypedEnvelope<StandaloneGroup>) {
+    managed_envelope
+        .envelope_mut()
+        .take_items_by(|i| *i.ty() == ItemType::FormData);
```
Comment (jjbayer) [inline relay-server/src/services/processor/standalone.rs]: nit: `managed_envelope.retain_items(|i| match i.ty() { ItemType::FormData => ItemAction::DropSilently, ... }` would be nice and explicit here.

File: relay-server/src/services/processor/standalone.rs [hunk 2]
```diff
@@ -0,0 +1,13 @@
+use crate::envelope::ItemType;
+use crate::services::processor::StandaloneGroup;
+use crate::utils::TypedEnvelope;
+
+/// Processes a standalone envelope by removing unnecessary items.
+///
+/// This function removes form data items from the envelope since they are not needed for
+/// standalone processing.
```
Comment (jjbayer) [inline relay-server/src/services/processor/standalone.rs]:
```suggestion
/// This function removes form data items from the envelope since they are not allowed in
/// standalone processing.
```

**Review by jjbayer — APPROVED** [review]
