### PR TITLE
fix(contexts): Normalize browser and os names with missing versions

### LINKED ISSUE #4956: Tag `os.name` should show up All events tab if `os` tag is not present.
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an event with context `{"os": {"name": "Any"}}`
2. Sending the event to sentry will automatically create a tag `os.name = Any`
3. Go to the Event -> All Events tab

### Expected Result

Tag `os.name` should show up as the value in the events table. Alternatively, this could be an ingestion issue where the given context should create the OS tag?

### Actual Result

Image

### Product Area

Issues

### Link

https://sentry-sdks.sentry.io/issues/6745534085/events/fdaf791ceec1411891d8530191bc3b4b/

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by Dav1dde**
Fixes: #4956

### CODE REVIEW

**Review by tobias-wilfert — APPROVED** [review]

**Comment by tobias-wilfert** [comment]
Looks like there is still some test and code that need to be modified for the CI to pass.

File: relay-event-normalization/src/normalize/contexts.rs [hunk 1]
```diff
@@ -543,8 +629,15 @@ mod tests {
...
-        assert_eq!(Some("10.1.23456"), os.version.as_str());
+        assert_json_context!(os, @r###"
+        {
+          "os": "Windows 10.1.23456",
+          "name": "Windows",
+          "version": "10.1.23456",
+          "build": "23456",
+          "raw_description": "Microsoft Windows 10.1.23456"
+        }
+        "###);
```
Comment (vaind) [inline relay-event-normalization/src/normalize/contexts.rs:640]: While not strictly related to the changes in this PR. It's weird that one of these gets parsed as Windows 11 and another with the full version number in the "os" context. Worth having a look.

Related to:
- https://github.com/getsentry/relay/issues/4492
- https://github.com/getsentry/relay/issues/1264

Or is it because we have a whitelist somewhere? I vaguely remember there being some code checking specific versions

File: relay-event-normalization/src/normalize/contexts.rs [hunk 2]
```diff
@@ -782,9 +965,13 @@ mod tests {
         };
 
         normalize_os_context(&mut os);
-        assert_eq!(Some("Nintendo OS"), os.name.as_str());
-        assert_eq!(None, os.version.value());
-        assert_eq!(None, os.build.value());
+        assert_json_context!(os, @r###"
+        {
+          "os": "Nintendo OS",
```
Comment (vaind) [inline relay-event-normalization/src/normalize/contexts.rs:970]: 👍

**Review by vaind — APPROVED** [review]

**Comment by vaind** [comment]
> Looks like there is still some test and code that need to be modified for the CI to pass.

To me this looks like it's only the Prospero test cases
