### PR TITLE
ref(kafka): Validate topics on startup

### LINKED ISSUE #3404: [INC-696] Validate Kafka configuration on startup
When Relay is configured to publish to a non-existing topic, it currently starts normally and only starts logging errors when traffic for that topic comes in.

Relay should fail startup when a Kafka topic does not exist.

Note: This issue is a narrower version of https://github.com/getsentry/relay/issues/2766.

### PR DESCRIPTION
**Pull request by Dav1dde**
This PR adds Kafka topics validation when Relay is starting up. This is done to prevent misconfiguration of Relay leading to errors when producing events.

Closes: #3404

### CODE REVIEW

File: relay-config/src/config.rs [hunk 1]
```diff
@@ -999,6 +999,9 @@ pub struct Processing {
     /// Kafka topic names.
     #[serde(default)]
     pub topics: TopicAssignments,
+    /// Whether to validate the supplied topics by calling Kafka's metadata endpoints.
+    #[serde(default)]
+    pub validate_kafka_topics: bool,
```
Comment (Dav1dde) [inline relay-config/src/config.rs]:
```suggestion
    pub kafka_validate_topics: bool,
```

File: relay-kafka/src/producer/mod.rs [hunk 2]
```diff
@@ -94,6 +102,22 @@ impl Producer {
             producer,
         }
     }
+
+    /// Validates the topic by fetching the metadata of the topic directly from Kafka.
+    fn validate_topic(&self) -> Result<(), ClientError> {
+        let client = self.producer.client();
+        let metadata = client
+            .fetch_metadata(Some(&self.topic_name), Duration::from_secs(5))
```
Comment (Dav1dde) [inline relay-kafka/src/producer/mod.rs]: Timeout?

File: relay-server/src/services/store.rs [hunk 3]
```diff
@@ -64,7 +66,9 @@ impl Producer {
             **t != KafkaTopic::Outcomes && **t != KafkaTopic::OutcomesBilling
         }) {
             let kafka_config = &config.kafka_config(*topic)?;
-            client_builder = client_builder.add_kafka_topic_config(*topic, kafka_config)?;
+            client_builder = client_builder
+                .add_kafka_topic_config(*topic, kafka_config, config.validate_kafka_topics())
+                .context(ServiceError::Kafka)?;
```
Comment (Dav1dde) [inline relay-server/src/services/store.rs:72]: Did you mean `map_err` here?

```suggestion
                .map_err(ServiceError::Kafka)?;
```

**Comment by Dav1dde** [comment]
:shipit:

File: relay-server/src/services/outcome.rs [hunk 4]
```diff
@@ -736,7 +736,7 @@ impl KafkaOutcomesProducer {
         for topic in &[KafkaTopic::Outcomes, KafkaTopic::OutcomesBilling] {
             let kafka_config = &config.kafka_config(*topic).context(ServiceError::Kafka)?;
             client_builder = client_builder
-                .add_kafka_topic_config(*topic, kafka_config)
+                .add_kafka_topic_config(*topic, kafka_config, config.kafka_validate_topics())
```
Comment (jjbayer) [inline relay-server/src/services/outcome.rs:818]: nit: To make this more builder pattern, it would be nice to have a method call outside of the loop

```rust
    .add_kafka_topic_config(*topic, kafka_config)
}

builder.set_topic_validation(conig.kafka_validate_topics());
builder.build()
```

File: tests/integration/test_config.py [hunk 5]
```diff
@@ -18,3 +18,13 @@ def test_invalid_kafka_config_should_fail(mini_sentry, relay_with_processing):
...
+
+
+def test_invalid_topics_raise_error(mini_sentry, relay_with_processing):
+    options = {"processing": {"kafka_validate_topics": True}}
+
+    relay = relay_with_processing(options=options, wait_health_check=False)
+    assert relay.wait_for_exit() != 0
+
+    error = str(mini_sentry.test_failures.pop(0))
+    assert "failed to validate the topic with name" in error
```
Comment (jjbayer) [inline tests/integration/test_config.py:30]: What topic does this fail on?

**Review by jjbayer — APPROVED** [review]
