### PR TITLE
fix(unreal): Fix unreal crash reporter OS names, improve os name parsing

### LINKED ISSUE #4834: Improve parsing of os.name for the `unreal` endpoint
And the [Unreal Engine Crash Reporter Client](https://docs.sentry.io/platforms/unreal/configuration/setup-crashreporter/), `unreal.crashreporter` 1.0.0 (relay endpoint):

```
"os": {
  "name": "Windows Server 2019 (Release 1809) [10.0.17763.6189]",
  "version": "10.0.17763",
  "type": "os"
},
```

This results in the search auto complete showing:

Image

Image

This also degrades our ability to show the issue distribution by OS, for example:

Image

While the additional data is valuable, like build number and full version number, the `os.name` ideally should be plain:

`os.name: Windows`

Similarly for Linux, also coming from `sentry-native`:

Image

As well as Mac, for example:

`sdk.name: unreal.crashreporter` version 1.0 (Relay endpoint):

```json
"os": {
  "name": "macOS 15.5",
  "raw_description": "Mac OS X 15.5 (24F74)",
  "type": "os"
},
```

Lastly another example I found was from Android:

```json
"os": {
  "name": "Android OS 12 / API-31 (STAS32.79-77-28-63-9/77-28-63-9)",
  "type": "os"
},
"os_family": {
  "name": "Other",
  "type": "os_family"
}
```

Relates to:
* https://github.com/getsentry/relay/issues/1004#issuecomment-874646799

### PR DESCRIPTION
**Pull request by Dav1dde**
Fixes: #4834

### CODE REVIEW

File: relay-event-normalization/src/normalize/contexts.rs [hunk 1]
```diff
@@ -221,20 +243,12 @@ fn normalize_os_context(os: &mut OsContext) {
...
         } else if let Some(captures) = OS_IPADOS_REGEX.captures(raw_description) {
             os.name = "iPadOS".to_string().into();
             os.version = captures
                 .name("version")
                 .map(|m| m.as_str().to_string())
                 .into();
-            os.build = captures
-                .name("build")
-                .map(|m| m.as_str().to_string().into())
-                .into();
```
Comment (Dav1dde) [inline relay-event-normalization/src/normalize/contexts.rs]: The regexes do not contain a `build` capture group

File: relay-event-normalization/src/normalize/contexts.rs [hunk 2]
```diff
@@ -11,7 +11,7 @@ use relay_protocol::{Annotated, Empty, Value};
 
 /// Environment.OSVersion (GetVersionEx) or RuntimeInformation.OSDescription on Windows
 static OS_WINDOWS_REGEX1: Lazy<Regex> = Lazy::new(|| {
-    Regex::new(r"^(Microsoft )?Windows (NT )?(?P<version>\d+\.\d+\.(?P<build_number>\d+)).*$")
+    Regex::new(r"^(Microsoft\s+)?Windows\s+(NT\s+)?(?P<version>\d+\.\d+\.(?P<build_number>\d+)).*$")
```
Comment (Dav1dde) [inline relay-event-normalization/src/normalize/contexts.rs:14]: Might as well match on `\s+` that catches a bit more and is also what the 2nd windows regex does.

File: relay-server/src/utils/unreal.rs [hunk 3]
```diff
@@ -238,7 +238,7 @@ fn merge_unreal_context(event: &mut Event, context: Unreal4Context) {
     // OS information is likely overwritten by Minidump processing later.
     if let Some(os_major) = runtime_props.misc_os_version_major.take() {
         let os_context = contexts.get_or_default::<OsContext>();
-        os_context.name = Annotated::new(os_major);
+        os_context.raw_description = Annotated::new(os_major);
```
Comment (loewenheim) [inline relay-server/src/utils/unreal.rs:241]: To be clear, this is the change that fixes the linked issue, right?

**Review by loewenheim — APPROVED** [review]

**Comment by loewenheim** [comment]
The clippy lint that gets tripped by this is honestly amazing: https://rust-lang.github.io/rust-clippy/master/index.html#almost_complete_range

File: relay-server/src/utils/unreal.rs (hunk 3 above)
Comment (Dav1dde) [reply relay-server/src/utils/unreal.rs:241]: This and the updated normalization logic, which needs to handle `Windows 10` (we had an unreal crash which had that string in an integration test).

**Comment by Dav1dde** [comment]
Damn, that is a life saver, I did it correctly for `0..=9` then missed it for `a..z`

**Comment by IanWoodard** [comment]
Reverting as this is believed to have broken Sentry CI: https://github.com/getsentry/sentry/actions/runs/16004441168/job/45147511159
