### PR TITLE
fix(config): Processing is only for managed mode

### LINKED ISSUE #3048: Forbid combination of proxy mode and processing in config
Apparently it is possible to run Relay with a combination of `mode: proxy` and `processing: enabled`. See https://github.com/getsentry/relay/issues/3033#issuecomment-1921441767.

We should catch this in a config validation step.

### PR DESCRIPTION
**Pull request by olksdr**
Proxy mode should not allow processing to be enabled. 

fix: https://github.com/getsentry/relay/issues/3048

#skip-changelog

### CODE REVIEW

**Review by Dav1dde — APPROVED** [review]

File: relay/src/setup.rs [hunk 1]
```diff
@@ -9,6 +9,13 @@ pub fn check_config(config: &Config) -> Result<()> {
         );
     }
 
+    if config.relay_mode() == RelayMode::Proxy && config.processing_enabled() {
+        anyhow::bail!(
+            "Processing mode cannot be enabled while in the proxy mode. \
```
Comment (jjbayer) [inline relay/src/setup.rs]:
```suggestion
            "Processing mode cannot be enabled while in proxy mode. \
```

File: relay/src/setup.rs [hunk 2]
```diff
@@ -9,6 +9,13 @@ pub fn check_config(config: &Config) -> Result<()> {
...
+            Please disable processing or switch to managed mode."
```
Comment (jjbayer) [inline relay/src/setup.rs]: This might incentivize users to enable processing in managed mode, so I would not even mention it here. Side note: Should `Processing` be a separate mode, i.e. variant of `RelayMode`, instead of a boolean flag?

```suggestion
            "
```

**Review by TBS1996 — APPROVED** [review]
