### PR TITLE
ref(registry): Remove global service registry

### LINKED ISSUE #1610: Fix tests depending on broken `SystemRegistry` behavior
```[tasklist]
### List of failing tests
- [ ] https://github.com/getsentry/relay/blob/1d57db414a11af96348747c307d40a7852018142/relay-server/src/actors/processor.rs#L2941
```

### PR DESCRIPTION
**Pull request by olksdr**
This PR finalizes migration to service dependencies injection instead of using the global registry.

In this part the changes mostly located in the endpoints, and their dependencies.

This also allowed to uncomment few `ignored` tests as they are no longer depend on the global registry or all the services. 

related to: https://github.com/getsentry/relay/issues/1818
fixes: https://github.com/getsentry/relay/issues/1610

### CODE REVIEW

File: relay-server/src/extractors/signed_json.rs [hunk 1]
```diff
@@ -77,7 +78,7 @@ where
     B: axum::body::HttpBody + Send + 'static,
     B::Data: Send,
     B::Error: Into<axum::BoxError>,
-    S: Send + Sync,
+    S: Send + Sync + ServiceRegistry,
```
Comment (jan-auer) [inline relay-server/src/extractors/signed_json.rs]: Instead of this trait, you can make this non-generic and require `ServiceState`. This is also what we do in a few other extractors.

File: relay-server/src/service.rs [hunk 2]
```diff
@@ -87,6 +90,7 @@ pub fn create_runtime(name: &str, threads: usize) -> Runtime {
 pub struct ServiceState {
     config: Arc<Config>,
```
Comment (jan-auer) [inline relay-server/src/service.rs:84]: `ServiceState` is cloned very often by axum, and also from us. Cloning it is somewhat expensive now, since we clone a lot of fields: All the runtimes, and then all fields in the registry. It would now make sense to change the internals of `ServiceState` to something like:


```rust
#[derive(Clone, Debug)]
struct ServiceState {
    inner: Arc<StateInner>,
}

impl ServiceState {
    // accessor methods for every service here, accessing through `self.inner.*`
}

#[derive(Debug)] // no Clone!
struct StateInner {
    // all Addrs here
    // all runtimes here
    // buffer guard
}
```

File: relay-server/src/actors/project_cache.rs [hunk 3]
```diff
@@ -819,12 +820,14 @@ impl Service for ProjectCacheService {
...
         let Self {
+            buffer_guard,
             config,
             services,
             redis,
         } = self;
-        let buffer_guard = services.buffer.clone();
         let project_cache = services.project_cache.clone();
+        let outcome_aggregator = services.outcome_aggregator.clone();
+        let test_store = services.test_store.clone();
```
Comment (iker-barriocanal) [inline relay-server/src/actors/project_cache.rs:830]: I see that we clone all the services. Is it to avoid issues with a mutable reference? Or, why are we doing that?

File: relay-server/src/actors/project_cache.rs [hunk 4]
```diff
@@ -835,16 +838,23 @@ impl Service for ProjectCacheService {
...
-                    Ok(buffer) => buffer.start(),
-                    Err(err) => {
-                        relay_log::error!("failed to start buffer service: {}", LogError(&err));
-                        // NOTE: The process will exit with error if the buffer file could not be
-                        // opened or the migrations could not be run.
-                        std::process::exit(1);
-                    }
-                };
+            let buffer = match BufferService::create(
+                buffer_guard,
```
Comment (iker-barriocanal) [inline relay-server/src/actors/project_cache.rs:842]: Not related to this PR, but I wonder if we could somehow abstract the buffer guard and make it part of the buffer service?

**Review by iker-barriocanal — CHANGES_REQUESTED** [review]
Out of scope for this PR, but `test_store` seems to me that it's related to tests. For this approach the PR looks good, a couple of questions to discuss wrt to the approach.

File: relay-server/src/actors/project_cache.rs (hunk 4 above)
Comment (olksdr) [reply relay-server/src/actors/project_cache.rs:842]: This is still in followups: https://github.com/getsentry/team-ingest/issues/53

File: relay-server/src/actors/project_cache.rs (hunk 3 above)
Comment (olksdr) [reply relay-server/src/actors/project_cache.rs:830]: The clone is very cheap here and in fact it's all the same objects, which just contains the inner rx channel and the counter for number of messages in the queue. This way each service can own the addresses of the services its communicate with.

File: relay-server/src/actors/project_cache.rs (hunk 4 above)
Comment (iker-barriocanal) [reply relay-server/src/actors/project_cache.rs:842]: Oh yeah my bad, I completely forgot we had that.

**Review by iker-barriocanal — APPROVED** [review]
