### PR TITLE
fix: Also build rdkafka with ssl if ssl feature is enabled

### LINKED ISSUE #879: Can't connect to Kafka broker using SSL
I'm using the docker image `getsentry/relay:20.11.1`

I'm trying to connect to a Kafka broker using SSL (port 9094), but Relay is reporting that my config file is invalid.

```yaml
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
  - name: bootstrap.servers
    value: 'kafka-b-2.sentry.:9094,kafka-b-1.sentry.:9094'
  - name: security.protocol
    value: ssl
  - name: message.max.bytes
    value: 50000000
relay:
  host: 0.0.0.0
  port: 3000
  upstream: http://web.sentry.:9000
```

```
# relay -V
relay 20.11.1
# relay run
 ERROR relay::cli > could not initialize kafka producer
  caused by: Client config error: Invalid value "ssl" for configuration property "security.protocol" security.protocol ssl
```

According to the [rdkafka docs](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) this should be a legal configuration property and value. 

Rdkafka claims this is an issue with the wrapper library: edenhill/librdkafka#1938 and rust-rdkafka states that you need to compile with the openssl library: fede1024/rust-rdkafka#174. Since I'm using the getsentry/relay official Docker image, this seems it would be an issue with this repository.

So far I've been able to get the Python components (Snuba and Sentry web) to run with SSL to Kafka, so this issue appears to be limited to Relay.

### PR DESCRIPTION
**Pull request by untitaker**
Fix https://github.com/getsentry/relay/issues/879

librdkafka can link exclusively against openssl, while relay's http stack actually uses native-tls abstraction which does not require openssl outside of linux (see relay's release page, we also offer standalone .exe outside of docker). This poses a problem for our local dev workflow, as all our workstations are OS X, have no OpenSSL, but we still want to compile Relay in processing mode. The solution is a separate featureflag `kafka-ssl`.

### CODE REVIEW

**Comment by ajacques** [comment]
I tried to build this version, but got this:

```
 ---> Running in a90130a73f3b
cd relay && cargo build --release --locked --features ssl,processing --target=x86_64-unknown-linux-gnu
    Updating crates.io index
    Updating git repository `https://github.com/getsentry/sentry-rust`
    Updating git repository `https://github.com/getsentry/rust-json-forensics`
    Updating git repository `https://github.com/luser/rust-minidump`
error: the lock file /work/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
make: *** [Makefile:27: build-linux-release] Error 101
```

Removing `--locked` to test it, then gives me:
```
error: failed to run custom build command for `rdkafka-sys v2.1.0+1.5.0`

Caused by:
  process didn't exit successfully: `/work/target/release/build/rdkafka-sys-6dd6a1c0ff593a0d/build-script-build` (exit code: 101)
  --- stdout
  Configuring and compiling librdkafka
  running: "cmake" "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-sys-2.1.0+1.5.0/librdkafka" "-DRDKAFKA_BUILD_STATIC=1" "-DRDKAFKA_BUILD_TESTS=0" "-DRDKAFKA_BUILD_EXAMPLES=0" "-DCMAKE_INSTALL_LIBDIR=lib" "-DWITH_ZLIB=1" "-DWITH_SSL=1" "-DWITH_SASL=0" "-DWITH_ZSTD=0" "-DENABLE_LZ4_EXT=0" "-DCMAKE_INSTALL_PREFIX=/work/target/x86_64-unknown-linux-gnu/release/build/rdkafka-sys-2e1dfde9b3fdaf16/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
  -- The C compiler identification is GNU 8.3.0
  -- The CXX compiler identification is GNU 8.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pow in m
  -- Looking for pow in m - found
  -- Could NOT find ZSTD (missing: ZSTD_LIBRARY ZSTD_INCLUDE_DIR) 
  -- Found ZLIB: /work/target/x86_64-unknown-linux-gnu/release/build/libz-sys-ba10cb51e4ee4672/out/build/libz.a (found version "1.2.11") 
  -- Configuring incomplete, errors occurred!
  See also "/work/target/x86_64-unknown-linux-gnu/release/build/rdkafka-sys-2e1dfde9b3fdaf16/out/build/CMakeFiles/CMakeOutput.log".
```

It's interesting how SSL works on the HTTP side, but not the Kafka side.

**Comment by untitaker** [comment]
@ajacques I think I figured it out, can you try again

**Comment by ajacques** [comment]
Not sure what I'm doing wrong, but it's still failing with the same error:
```
[ec2-user@ip-10-0-28-70 relay]$ git status
On branch fix/rdkafka-ssl
Your branch is up to date with 'origin/fix/rdkafka-ssl'.

nothing to commit, working tree clean
[ec2-user@ip-10-0-28-70 relay]$ git rev-parse HEAD
05729ab5df4d8f11781a8c7dd713b8ed8cdae5c5
```

```
error: failed to run custom build command for `rdkafka-sys v2.1.0+1.5.0`

Caused by:
  process didn't exit successfully: `/work/target/release/build/rdkafka-sys-6dd6a1c0ff593a0d/build-script-build` (exit code: 101)
  --- stdout
  Configuring and compiling librdkafka
  running: "cmake" "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-sys-2.1.0+1.5.0/librdkafka" "-DRDKAFKA_BUILD_STATIC=1" "-DRDKAFKA_BUILD_TESTS=0" "-DRDKAFKA_BUILD_EXAMPLES=0" "-DCMAKE_INSTALL_LIBDIR=lib" "-DWITH_ZLIB=1" "-DWITH_SSL=1" "-DWITH_SASL=0" "-DWITH_ZSTD=0" "-DENABLE_LZ4_EXT=0" "-DCMAKE_INSTALL_PREFIX=/work/target/x86_64-unknown-linux-gnu/release/build/rdkafka-sys-2e1dfde9b3fdaf16/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
  -- The C compiler identification is GNU 8.3.0
  -- The CXX compiler identification is GNU 8.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pow in m
  -- Looking for pow in m - found
  -- Could NOT find ZSTD (missing: ZSTD_LIBRARY ZSTD_INCLUDE_DIR) 
  -- Found ZLIB: /work/target/x86_64-unknown-linux-gnu/release/build/libz-sys-ba10cb51e4ee4672/out/build/libz.a (found version "1.2.11") 
  -- Configuring incomplete, errors occurred!
  See also "/work/target/x86_64-unknown-linux-gnu/release/build/rdkafka-sys-2e1dfde9b3fdaf16/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  Building and linking librdkafka statically
  CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
    Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
    system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
    OPENSSL_INCLUDE_DIR)
  Call Stack (most recent call first):
    /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.13/Modules/FindOpenSSL.cmake:412 (find_package_handle_standard_args)
    src/CMakeLists.txt:226 (find_package)


  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.44/src/lib.rs:885:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:27: build-linux-release] Error 101

```

**Comment by untitaker** [comment]
no sorry you're right, this is a problem inside of the docker image. I am not sure what's going on though, why rust-rdkafka does not link properly against openssl while clearly all the other stuff can. It even uses the same crate (openssl-sys) to find the openssl installation

**Comment by untitaker** [comment]
@ajacques can you try again. This time it actually builds for me.

**Comment by ajacques** [comment]
We have success! I was able to connect to my broker over SSL using this latest commit.

File: relay/src/main.rs [hunk 1]
```diff
@@ -21,9 +21,21 @@
...
 //! - `processing`: Includes event ingestion and processing functionality. This should only be
-//!   specified when compiling Relay as Sentry service. Standalone Relays do not need this feature.
+//!   specified when compiling Relay as Sentry service.  Standalone Relays do not need this feature.
+//!
+//! - `kafka-ssl`: Our Kafka client `librdkafka` requires OpenSSL on *all* platforms to speak SSL.
+//!   As this is an extra requirement on Windows and Mac it is its own featureflag and disabled by
+//!   default.
+//!
+//!   This feature is only relevant when Relay is compiled with `processing` enabled, as without it
+//!   `librdkafka` is not installed.
```
Comment (jan-auer) [inline relay/src/main.rs]:
```suggestion
//! - `kafka-ssl`: This feature is only relevant in combination with `processing`. 
//!   The Kafka client `librdkafka` requires OpenSSL on *all* platforms to speak SSL.
//!   As this is an extra requirement on Windows and Mac, this is disabled by default.

```

File: Dockerfile [hunk 2]
```diff
@@ -63,7 +63,9 @@ RUN echo "Building OpenSSL" \
 FROM getsentry/sentry-cli:1 AS sentry-cli
 FROM relay-deps AS relay-builder
 
-ARG RELAY_FEATURES=ssl,processing
+# ssl and processing are required for basic functionality in onprem
```
Comment (jan-auer) [inline Dockerfile:69]: This is not exactly true, our onprem setup works well without `kafka-ssl`. I would even go as far and not build Relay with kafka-ssl as I see this as a severe edge case; however, if you are confident that there are no side effects, we can leave it on.

**Review by jan-auer — APPROVED** [review]

File: Dockerfile (hunk 2 above)
Comment (untitaker) [reply Dockerfile:69]: yeah by the comment I mean `processing` and `ssl` are required, `kafka-ssl` is no extra cost to add
