### PR TITLE
fix(pii): Ignore `replacement_chunks` when they aren't used [INGEST-109]

### LINKED ISSUE #1095: error processing envelope: could not schedule project fetch caused by: Mailbox has closed
### Environment
Sentry 21.6.3
Relay 21.6.3
Snuba 21.6.3

Issue:
-----
After certain load treshold relay is failing to a state that it's not able to recover from, until restarted (by the way the exact same behavior is there at least from 20.8.0):

===Cut===
[...]
Sep 29 06:25:52 jsentry relay[62139]: 2021-09-29T06:25:52Z [relay_server::actors::upstream] INFO: relay successfully registered with upstream
Sep 29 06:26:07 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:07 jsentry relay[62139]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 29 06:26:07 jsentry relay[62139]: 2021-09-29T06:26:07Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:07 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:26:09 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:09 jsentry relay[62139]: 2021-09-29T06:26:09Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:09 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:26:09 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:09 jsentry relay[62139]: 2021-09-29T06:26:09Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:09 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:26:09 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:09 jsentry relay[62139]: 2021-09-29T06:26:09Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:09 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:26:09 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:09 jsentry relay[62139]: 2021-09-29T06:26:09Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:09 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:23 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:27:23 jsentry relay[62139]: 2021-09-29T06:27:23Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:23 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:24 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:27:24 jsentry relay[62139]: 2021-09-29T06:27:24Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:24 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:25 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:27:25 jsentry relay[62139]: 2021-09-29T06:27:25Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:25 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:25 jsentry relay[62139]: 2021-09-29T06:27:25Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:25 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:26 jsentry relay[62139]: 2021-09-29T06:27:26Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:26 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:27 jsentry relay[62139]: 2021-09-29T06:27:27Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
===Cut===

### PR DESCRIPTION
**Pull request by iker-barriocanal**
With ReplaceBehavior::Value, we only want to replace a string value.
This means we don't need the replacement chunks since
`insert_replacement_chunks` correctly adds the replacement and the
`process_text` function is useless because we don't need it (besides,
processing an empty string doesn't perform any action).

Now that the `replacement_chunks` are only needed in
ReplaceBehavior::Groups, we can move the processing and assertion we do
on them to that branch of the `match`. This solves the issue of
asserting on them when we don't use them.

Fixes https://github.com/getsentry/relay/issues/1095.

### CODE REVIEW

**Review by untitaker — COMMENTED** [review]
lgtm assuming the test fails if the fix is not applied. ship it!

**Review by untitaker — APPROVED** [review]

File: relay-general/src/pii/processor.rs [hunk 1]
```diff
@@ -304,17 +304,17 @@ fn apply_regex_to_chunks<'a>(
...
-            process_text("", &mut rv, &mut replacement_chunks);
+            // We only want to replace a string value, and the replacement chunk for that is
+            // inserted by insert_replacement_chunks. Adding chunks from replacement_chunks
+            // results in the incorrect behavior of a total of more chunks than the input.
             insert_replacement_chunks(rule, &search_string, &mut rv);
-            pos = search_string.len();
         }
     }
 
-    process_text(&search_string[pos..], &mut rv, &mut replacement_chunks);
```
Comment (jjbayer) [inline relay-general/src/pii/processor.rs:315]: Are we sure we can remove this line for the `ReplaceBehavior::Groups` case? What if there are replacement chunks after the last matched group?

Comment (untitaker) [reply relay-general/src/pii/processor.rs:315]: it moved up to line 307, no?

Comment (jjbayer) [reply relay-general/src/pii/processor.rs:315]: Thanks, my bad.

**Review by jjbayer — APPROVED** [review]
