### PR TITLE
fix(eap): Normalize attributes as early as possible

### LINKED ISSUE #5871: eap: Normalize attributes first thing
* For spans, we currently run both `normalize_sentry_op` and `normalize_span_category` before `normalize_attribute_types` and `normalize_attribute_names`.
* For trace metrics, we currently run `normalize_attribute_types` after everything else, and `normalize_attribute_names` not at all.

Normalizing of attribute types and names should run as early as possible so other normalizations can rely on attributes being present under non-deprecated names.

### PR DESCRIPTION
**Pull request by loewenheim**
For all EAP items, the functions `normalize_attribute_types` and `normalize_attribute_names` should run before other normalization passes that access attributes. That way, they can rely on attributes being present under their "proper" names.

The tests in 3333412051c67e78dde960d5629de75298396d43 show what can go wrong if we don't normalize attributes first. 3ca5db536df4387a0c595a157069a645b097f76c contains the fix.

Fixes #5871. Fixes RELAY-224. 

This also bumps `sentry-conventions` to commit `3bb32d` to get access to https://github.com/getsentry/sentry-conventions/pull/332.

### CODE REVIEW

File: relay-server/src/processing/spans/process.rs [hunk 1]
```diff
@@ -293,8 +293,9 @@ mod tests {
     use relay_conventions::{
         APP_VITALS_START_TYPE, APP_VITALS_START_VALUE, APP_VITALS_TTFD_VALUE, DB_QUERY_TEXT,
         DB_SYSTEM, DB_SYSTEM_NAME, DESCRIPTION, DEVICE_CLASS, DEVICE_FAMILY, DEVICE_MODEL,
-        HTTP_REQUEST_METHOD, OP, SENTRY_ACTION, SENTRY_CATEGORY, SENTRY_DOMAIN, SENTRY_MAIN_THREAD,
-        SENTRY_MOBILE, SENTRY_NORMALIZED_DESCRIPTION, SENTRY_SDK_NAME, THREAD_NAME, URL_FULL,
+        GEN_AI_PROVIDER_NAME, GEN_AI_SYSTEM, HTTP_REQUEST_METHOD, OP, SENTRY_ACTION,
+        SENTRY_CATEGORY, SENTRY_DOMAIN, SENTRY_MAIN_THREAD, SENTRY_MOBILE,
+        SENTRY_NORMALIZED_DESCRIPTION, SENTRY_SDK_NAME, SPAN_KIND, THREAD_NAME, URL_FULL,
```
Comment (Dav1dde) [inline relay-server/src/processing/spans/process.rs]: Might as well:

```rs
use relay_conventions::consts::*
```

**Review by Dav1dde — APPROVED** [review]

File: relay-server/src/processing/spans/process.rs (hunk 1 above)
Comment (loewenheim) [reply relay-server/src/processing/spans/process.rs]: Good call.

**Comment by loewenheim** [comment]
The scope of this PR has expanded somewhat: it now also double-writes the attributes `browser.name`/`sentry.browser.name` and `browser.version`/`sentry.browser.verison` in `normalize_user_agent`. I'm not extremely happy about this, but I don't see a way around this for now—the `sentry.*` attributes are deprecated, but they're used downstream.

File: relay-event-normalization/src/eap/mod.rs [hunk 2]
```diff
@@ -244,10 +248,26 @@ pub fn normalize_user_agent(
...
     let attributes = attributes.get_or_insert_with(Default::default);
 
-    if attributes.contains_key(BROWSER_NAME) || attributes.contains_key(BROWSER_VERSION) {
+    if attributes.contains_key(SENTRY_BROWSER_NAME)
+        || attributes.contains_key(SENTRY_BROWSER_VERSION)
+    {
         return;
     }
 
+    // Backfill `sentry.browser.name` from `sentry.browser.name`, if available.
```
Comment (jjbayer) [inline relay-event-normalization/src/eap/mod.rs]:
```suggestion
    // Backfill `sentry.browser.name` from `browser.name`, if available.
```

File: relay-event-normalization/src/eap/mod.rs [hunk 3]
```diff
@@ -244,10 +248,26 @@ pub fn normalize_user_agent(
...
+    if let Some(name) = attributes.get_attribute(BROWSER_NAME) {
+        attributes
+            .0
+            .insert(SENTRY_BROWSER_NAME.to_owned(), name.clone().into());
+    }
+
+    // Backfill `sentry.browser.version` from `sentry.browser.version`, if available.
```
Comment (jjbayer) [inline relay-event-normalization/src/eap/mod.rs]:
```suggestion
    // Backfill `sentry.browser.version` from `browser.version`, if available.
```

File: relay-server/src/processing/spans/process.rs [hunk 4]
```diff
@@ -210,13 +210,13 @@ fn normalize_span(
 
         validate_timestamps(span)?;
 
+        eap::normalize_attribute_types(&mut span.attributes);
+        eap::normalize_attribute_names(&mut span.attributes);
```
Comment (jjbayer) [inline relay-server/src/processing/spans/process.rs:214]: I didn't double check, these two functions do not rely on any of the normalization steps below I assume?

**Review by jjbayer — APPROVED** [review]

**Review by Dav1dde — APPROVED** [review]
Is the backfill necessary or does coaelsece in Snuba/EAP take care of the query side well enough?

**Comment by loewenheim** [comment]
I've reverted the browser backfilling change, to be addressed at a later point.
