### PR TITLE
fix(pii): prevent ip derivation if already scrubbed before

### LINKED ISSUE #4480: Can't scrub user ip address when platform is javascript
# Description

I'm running relay in static mode with the goal of scrubbing the users ip address.
Sadly, this does not work when the platform is `javascript`. If I choose any other platform, it works as expected. The only thing I could get working was replacing the ip with a different, valid ip address.

# Reproduction

I'm using this project config:

```json
 {
  "slug": "...",
  "publicKeys": [
    {
      "publicKey": "...",
      "isEnabled": true
    }
  ],
  "config": {
    "allowedDomains": ["*"],
    "piiConfig": {
      "applications": {
        "$user.ip_address": ["@ip:hash"]
      }
    }
  }
}
```

In all cases, I use sentry-cli to send in a raw event with `sentry-cli send-event --raw ./event.json`

## Case Javascript Platform

Having `user.ip_address` set to `{{auto}}` or omitting it makes no difference here, but I kept it to have all events as similar as possible.

event:

```json
{
  "event_id": "97f605976f574848b1373355103e5830",
  "timestamp": 1738158010.77,
  "platform": "javascript",
  "environment": "development",
  "logentry": {
    "message": "foobar"
  },
  "user": {
    "ip_address": "{{auto}}"
  }
}
```

sentry issue content:

```json
{
  "event_id": "97f605976f574848b1373355103e5830",
  "platform": "javascript",
  ...
  "_meta": {
    "user": {
      "id": {
        "": {
          "rem": [
            [
              "@ip:hash",
              "p",
              0, 40]
          ],
          "len": 10
        }
      }
    }
  },
  ...
  "user": {
    "id": "2113688C79F19B2E4E5387DF571AF6F5FADEA223",
    "ip_address": "172.17.0.1",
    "sentry_user": "id:2113688C79F19B2E4E5387DF571AF6F5FADEA223"
  },
  ...
}
```

## Case Native Platform

event:

```json
{
  "event_id": "e6748bb459934515a774221125bea8dc",
  "timestamp": 1738158110.77,
  "platform": "native",
  "environment": "development",
  "logentry": {
    "message": "foobar"
  },
  "user": {
    "ip_address": "{{auto}}"
  }
}

```

sentry issue content

```json
{
  "event_id": "e6748bb459934515a774221125bea8dc",
  "platform": "native",
  ...
  "_meta": {
    "user": {
      "id": {
        "": {
          "rem": [
            [
              "@ip:hash",
              "p",
              0, 40]
          ],
          "len": 10
        }
      }
    }
  },
  ...
  "user": {
    "id": "2113688C79F19B2E4E5387DF571AF6F5FADEA223",
    "sentry_user": "id:2113688C79F19B2E4E5387DF571AF6F5FADEA223"
  },
  ...
}
```

### PR DESCRIPTION
**Pull request by Litarnus**
This PR adds remarks if the user IP was PII scrubbed to prevent assuming that empty IP means `{{auto}}` for certain platforms.

fix https://github.com/getsentry/relay/issues/4480

### CODE REVIEW

File: relay-event-normalization/src/event.rs [hunk 1]
```diff
@@ -460,9 +460,17 @@ pub fn normalize_ip_addresses(
...
         if user.ip_address.value().is_none() {
-            // In an ideal world all SDKs would set {{auto}} explicitly.
-            if let Some("javascript") | Some("cocoa") | Some("objc") = platform {
-                user.ip_address = Annotated::new(client_ip.to_owned());
+            // Only assume that empty means {{auto}} if there is no remark that the IP address has been removed.
+            let scrubbed_before = user
+                .ip_address
+                .meta()
+                .iter_remarks()
+                .any(|r| r.ty == RemarkType::Removed && r.rule_id() == "pii:ip_address");
```
Comment (Dav1dde) [inline relay-event-normalization/src/event.rs]: Do we care what rule removed it?

Comment (Litarnus) [reply relay-event-normalization/src/event.rs]: No I don't think so, good point!

**Review by jjbayer — COMMENTED** [review]
We should have a test case for this, maybe an integration test using `relay_chain`?

File: relay-event-normalization/src/event.rs [hunk 2]
```diff
@@ -460,9 +460,17 @@ pub fn normalize_ip_addresses(
...
-                user.ip_address = Annotated::new(client_ip.to_owned());
+            // Only assume that empty means {{auto}} if there is no remark that the IP address has been removed.
+            let scrubbed_before = user
+                .ip_address
+                .meta()
+                .iter_remarks()
+                .any(|r| r.ty == RemarkType::Removed);
+            if !scrubbed_before {
+                // In an ideal world all SDKs would set {{auto}} explicitly.
+                if let Some("javascript") | Some("cocoa") | Some("objc") = platform {
```
Comment (loewenheim) [inline relay-event-normalization/src/event.rs:471]: I don't think I've ever seen `if let` used with this sort of pattern before.

**Review by jjbayer — APPROVED** [review]

File: relay-event-normalization/src/event.rs (hunk 2 above)
Comment (Litarnus) [reply relay-event-normalization/src/event.rs:471]: Me neither, but I like its expressiveness
