### PR TITLE
test: Identify correct UA with enabled data scrubbing.

### LINKED ISSUE #1375: UA reduction is resulting in Chrome versions being matched as IPs, breaking agent detection
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry.javascript.react, 7.8.1

### Steps to Reproduce

Regular usage, with regular users, on the latest Chrome

### Expected Result

UAs are processed normally, and browser detection is successfully done based on it

### Actual Result

UAs have the version redacted as they match the IP regex

-----

With [UA reduction](https://www.chromium.org/updates/ua-reduction/), Chromium user-agents are being transformed from, eg, `103.0.5060.140` to `103.0.0.0`.  This results in the relay redacting the UA string as it matches the IP regex:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[ip] Safari/537.36`

This results in the browser being detected as Safari rather than Chrome.

### PR DESCRIPTION
**Pull request by olksdr**
With [UA reduction](https://www.chromium.org/updates/ua-reduction) Chromium user agent transformed to the form that looks like IPv4 address and it triggers PII scrubbing rules.

This test makes sure that even when the data must be scrubbed, we still can properly identify browser vendor and version.

The issue was basically fixed before, see https://github.com/getsentry/relay/issues/1375#issuecomment-1203676355 , and now we just want to make sure we have a test and won't have regressions in the future. 

fix: https://github.com/getsentry/relay/issues/1375

#skip-changelog

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

File: relay-server/src/actors/processor.rs [hunk 1]
```diff
@@ -2315,6 +2316,96 @@ mod tests {
...
+            );
+            item
+        });
+
+        let new_envelope = relay_test::with_system(move || {
+            let mut scrub_config = DataScrubbingConfig::default();
+            // enable all the default scrubbing
+            scrub_config.scrub_data = true;
+            scrub_config.scrub_defaults = true;
+            scrub_config.scrub_ip_addresses = true;
```
Comment (iker-barriocanal) [inline relay-server/src/actors/processor.rs]: Can we merge these into the object creation, just as you do with the project config? It'd look something like this:
```suggestion
            let mut scrub_config = {
              scrub_data: true,
              scrub_defaults: true,
              scrub_ip_addresses: true,
              ..DataScrubbingConfig::default()
            };
```

File: relay-server/src/actors/processor.rs [hunk 2]
```diff
@@ -2315,6 +2316,96 @@ mod tests {
...
+                r##"
+                {
+                    "applications": {
+                        "**": ["@ip:mask"]
+                    }
+                }
+                "##,
+            )
+            .unwrap();
+            config.pii_config = Some(pii_config);
```
Comment (iker-barriocanal) [inline relay-server/src/actors/processor.rs]: Similar to previous, can we do something like the following?
```rust
let pii_config = PiiConfig......;
let mut config = ProjectConfig {
    datascrubbing_settings: scrub_config,
    pii_config,
    ..Default::default()
};
```

**Review by iker-barriocanal — APPROVED** [review]
Looks good, just a couple of nits.

File: relay-server/src/actors/processor.rs (hunk 1 above)
Comment (olksdr) [reply relay-server/src/actors/processor.rs]: We can't,  because field `pii_config` of struct `DataScrubbingConfig` is private

File: relay-server/src/actors/processor.rs (hunk 2 above)
Comment (olksdr) [reply relay-server/src/actors/processor.rs]: I can move this around
