### PR TITLE
fix(pii): Replace only user in the userpath

### LINKED ISSUE #2722: Large/Wrong truncation of `userpath` on PII on some path patterns
### Environment

relay 23.10.1, Rust 1.73.0

### Steps to Reproduce

1. Have a `PiiProcessor` compiled with `@userpath` in the config applications
2. Have this kind of string to do PII removal on
    ```
    make
    export PATH=$PATH:$HOME/collectd_exporter
    line
    line
    line
    line
    line
    ```

### Expected Result

Have 

    ```
    make
    export PATH=$PATH:$HOME/[user]
    line
    line
    line
    line
    line
    ```
### Actual Result

    ```
    make
    export PATH=$PATH:$HOME/[user]
    ```
    
 ### Code to reproduce
 
 ```rs
         let mut config = PiiConfig::default();
        config.applications = {
            let mut map = BTreeMap::new();
            map.insert(
                ValueType::String.into(),
                vec![
                    "@iban".into(),
                    "@ip".into(),
                    "@email".into(),
                    "@creditcard".into(),
                    "@pemkey".into(),
                    "@urlauth".into(),
                    "@userpath".into(),
                    "@password".into(),
                    "@usssn".into(),
                ],
            );
            map
        };

        let state = &STATE;
        let input = "make
export PATH=$PATH:$HOME/collectd_exporter
log
log
log
log
"
        .to_string();
        let compiled = config.compiled();
        let mut processor = PiiProcessor::new(compiled);
        let mut root = Annotated::new(input);
        process_value(&mut root, &mut processor, state).unwrap();
        println!("{root:?}");
 ```

### PR DESCRIPTION
**Pull request by olksdr**
Explicitly use only allowed characters for the username. 

Currently we replace everything till between the slashes, and if the slash after username is missing we will replace everything till the end of the input string. 

fix: https://github.com/getsentry/relay/issues/2722

#skip-changelog

### CODE REVIEW

File: relay-pii/src/regexes.rs [hunk 1]
```diff
@@ -231,7 +231,7 @@ static PATH_REGEX: Lazy<Regex> = Lazy::new(|| {
                 )
             )
             (
-                [^/\\]+
+                [A–Za-z0–9'\._!\#^~-]+
```
Comment (TBS1996) [inline relay-pii/src/regexes.rs]: I think this would stop at first space? and I believe spaces are allowed in windows usernames. Should it also be in the list of allowed characters? 

I checked on regex101 for this

Comment (Dav1dde) [reply relay-pii/src/regexes.rs]: Maybe should match anything until `\` or newline.

Edit: did this ever work on Windows with backwards slashes for path separators?

Comment (olksdr) [reply relay-pii/src/regexes.rs]: @TBS1996  Overall it's not advisable to have spaces in the usernames and I'm not sure we want to support it either. 
@Dav1dde  Also if we remove everything , or just will new line we again end up with a somewhat wrong scrubbing. 

See for example changes in `relay-server/tests/snapshots/test_fixtures__dotnet__pii_stripping.snap` below - it was scrubbed kind of a little bit too much. I do not mind that either, but we have to agree on the final rule 😄

Comment (olksdr) [reply relay-pii/src/regexes.rs]: included also space in the regex now

**Review by Dav1dde — APPROVED** [review]

**Review by iker-barriocanal — APPROVED** [review]
