### PR TITLE
fix(http): Explain why we responded with 429

### LINKED ISSUE #37103: Provide a status text containing the reason for HTTP 429
### Problem Statement

Our backend returns an HTTP error 429 when some rate limit/quota of our [public API](https://docs.sentry.io/api/) is reached. 
There is no more information about the reason.

### Solution Brainstorm

Return a status text that contains information about which rate limit was reached.

### PR DESCRIPTION
**Pull request by untitaker**
fix https://github.com/getsentry/sentry/issues/37103

Oftentimes we are not in control of the HTTP response (load balancers and relay may reject the request for a variety of reasons, and it would probably be quite a bit of effort to add docs links to all of those return paths), but if we
are, we can provide a more helpful error message.

The context here is that a customer was confused about whether the
network errors in Chrome's dev console would have any impact on their
application. While we can't influence the color of what is shown in the
dev console, we can provide documentation links in request/response
details. This will still be quite hidden but better than nothing.

Other ideas were to stop emitting 429s, but we could only do that for
browser, mobile and other "client" SDKs. For server-side SDKs we _need_
them to see a 429 so they stop sending data. And even then that change
would come with high risk of multiplying inbound traffic by a large
factor.

### CODE REVIEW

**Review by flub — APPROVED** [review]

File: relay-server/src/endpoints/common.rs [hunk 1]
```diff
@@ -73,7 +73,9 @@ pub enum BadStoreRequest {
     #[fail(display = "failed to read request body")]
     PayloadError(#[cause] PayloadError),
 
-    #[fail(display = "event rejected due to rate limit")]
+    #[fail(
+        display = "sentry dropped data due to a quota or internal rate limit being reached. this will not affect your application. see https://docs.sentry.io/product/accounts/quotas/ for more information."
```
Comment (jjbayer) [inline relay-server/src/endpoints/common.rs]:
```suggestion
        display = "Sentry dropped data due to a quota or internal rate limit being reached. This will not affect your application. See https://docs.sentry.io/product/accounts/quotas/ for more information."
```

**Review by jjbayer — APPROVED** [review]

**Review by iker-barriocanal — APPROVED** [review]
