### PR TITLE
fix(minidump): Respond with 413 for large chunked requests

### LINKED ISSUE #5838: minidump endpoint does not respond 413 for too large content
While changing the Native SDK to handle HTTP 413 Content Too Large ([NATIVE-160](https://linear.app/getsentry/issue/NATIVE-160/sdk-handling-http-413-native)), we found out that unlike `/envelope/`, the `/minidump/` endpoint doesn't respond with 413 but with 400 + reason in the body:

```
[ERROR http_transport_mac.mm:259] HTTP status 400, response = "{"detail":"invalid multipart data","causes":["stream size exceeded limit: 209715200 bytes"]}"
```

Is it possible to make the minidump endpoint respond 413? Not sure if this is intentional or a miss, but I thought I'd open a ticket and see where it takes us. :)

\_Originally posted by @jpnurmi in [https://github.com/getsentry/sentry-native/issues/1647#issuecomment-4245553301\_](<https://github.com/getsentry/sentry-native/issues/1647#issuecomment-4245553301_>)

### PR DESCRIPTION
**Pull request by jjbayer**
Large streaming requests were already capped by `RequestBodyLimit`, but the error for the interrupted stream surfaces somewhere deep within the code. Catch the error using the existing `find_error_source` util.

Closes https://github.com/getsentry/relay/issues/5838

### CODE REVIEW

**Review by tobias-wilfert — APPROVED** [review]

File: relay-server/src/endpoints/common.rs [hunk 1]
```diff
@@ -59,7 +61,7 @@ pub enum BadStoreRequest {
     InvalidEnvelope(#[from] EnvelopeError),
 
     #[error("invalid multipart data")]
-    InvalidMultipart(#[from] multer::Error),
+    InvalidMultipart(multer::Error),
```
Comment (jjbayer) [inline relay-server/src/endpoints/common.rs]:
```suggestion
    InvalidMultipart(#[source] multer::Error),
```
