### PR TITLE
fix: Normalize route path in trace context data

### LINKED ISSUE #3000: `contexts.trace.data.route` getting rejected by Sentry
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.13.1

### Steps to reproduce

1. Trigger an event that sends a trace to Sentry.
2. Observe the trace details in the Sentry issue interface.
3. The `contexts.trace.data.route` field does not contain the actual route name.

### Expected result

contexts.trace.data.route should contain route name

### Actual result

obrazek

```
{
http.flavor: 1.1,
 http.request.method: GET, 
 http.url: ...,
net.host.name: ..., 
net.host.port: 443, 
net.peer.ip: ..., 
route: None
}
```

### PR DESCRIPTION
**Pull request by olksdr**
Relay expects for `contexts.trace.data.route` to be a route, but some SDKs sent the string (for route names) in `route` and we want to handle this and normalize the data into the know types structure. 

This PR introduces the customer `FromValue` trait implementation for `Route` to handle:
* incoming object
* incoming string for `contexts.trace.data.route` field

fix: [#3000](https://github.com/getsentry/relay/issues/3000)

### CODE REVIEW

File: relay-event-schema/src/protocol/contexts/trace.rs [hunk 1]
```diff
@@ -170,6 +173,44 @@ pub struct Route {
...
+
+                if !values.is_empty() {
+                    route.other = values;
+                }
+
+                Annotated(Some(route), meta)
+            }
+            Annotated(None, meta) => Annotated(None, meta),
+            Annotated(Some(value), mut meta) => {
+                meta.add_error(Error::expected("route"));
```
Comment (iker-barriocanal) [inline relay-event-schema/src/protocol/contexts/trace.rs]: nit (not sure if the message is the most helpful one):
```suggestion
                meta.add_error(Error::expected("route expected to be an object"));
```

**Review by iker-barriocanal — APPROVED** [review]
Thanks for the fix!

I wonder if we should document this in the [trace context](https://develop.sentry.dev/sdk/event-payloads/contexts/#trace-context) to avoid similar issues in the future.

**Comment by olksdr** [comment]
> Thanks for the fix!
> 
> I wonder if we should document this in the [trace context](https://develop.sentry.dev/sdk/event-payloads/contexts/#trace-context) to avoid similar issues in the future.

added docs https://github.com/getsentry/develop/pull/1157

**Review by iker-barriocanal — APPROVED** [review]

**Review by Dav1dde — APPROVED** [review]
