### PR TITLE
Extend GPU context with data for Unreal Engine crash reports

### LINKED ISSUE #27498: Unreal Crash Report: Incorrect graphics card.
### Environment

self-hosted (`onpremise` deployment)

### Version

21.6.3

### Steps to Reproduce

When a user has an integrated graphics and a dedicated graphics card the `Misc.PrimaryGPUBrand` field in the `CrashContext.runtime-xml` may be populated with the integrated graphics card. Instead the `RHI.AdapterName` from the `EngineData` should be chosen which is the one running the game with. 

It would also be very helpful if the `RHI.UserDriverVersion` and `RHI.DriverDate` would be shown in the web interface.

### Expected Result

The chosen dedicated graphics card is shown.

### Actual Result

The integrated graphics card is shown.

### PR DESCRIPTION
**Pull request by slonopotamus**
1. This commit replaces primary GPU with the one that is actually used for rendering. These two may be different for laptops. Fixes https://github.com/getsentry/sentry/issues/27498
2. This commit adds other available data:
  * Numeric DeviceID
  * Used feature level (SM5, SM6, etc)
  * GPU vendor name
  * GPU driver version
  * RHI type that is used (Metal, Vulkan, DX11, etc)

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

File: relay-server/src/utils/unreal.rs [hunk 1]
```diff
@@ -212,9 +212,35 @@ fn merge_unreal_context(event: &mut Event, context: Unreal4Context) {
         os_context.name = Annotated::new(os_major);
     }
 
-    if let Some(gpu_brand) = runtime_props.misc_primary_gpu_brand.take() {
+    // See https://github.com/EpicGames/UnrealEngine/blob/5.3.2-release/Engine/Source/Runtime/RHI/Private/DynamicRHI.cpp#L368-L376
+    if let Some(adapter_name) = context.engine_data.get("RHI.AdapterName") {
```
Comment (Dav1dde) [inline relay-server/src/utils/unreal.rs:216]: Does it make sense to have a fallback to `runtime_props.misc_primary_gpu_brand` if the adapter name is not available?

E.g. with a quick google search I found a report [here](https://forums.unrealengine.com/t/cannot-open-epic-games-launcher-on-m1-macbook-air/482663/10) which does not contain `EngineData`

**Comment by slonopotamus** [comment]
Updated PR to include a changelog entry

File: relay-server/src/utils/unreal.rs (hunk 1 above)
Comment (slonopotamus) [reply relay-server/src/utils/unreal.rs:216]: Agreed, added a fallback to `runtime_props.misc_primary_gpu_brand`

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,10 +2,15 @@
...
 
+**Features**:
+
+- Extend GPU context with data for Unreal Engine crash reports ([#3144](https://github.com/getsentry/relay/pull/3144))
+
 **Bug Fixes**:
 
 - Forward metrics in proxy mode. ([#3106](https://github.com/getsentry/relay/pull/3106))
 - Do not PII-scrub code locations by default. ([#3116](https://github.com/getsentry/relay/pull/3116))
+- Use actually used GPU instead of the primary one for Unreal Engine crash reports ([#3144](https://github.com/getsentry/relay/pull/3144))
```
Comment (Dav1dde) [inline CHANGELOG.md]: I think it's fine if we just have the `Feature` entry.

File: CHANGELOG.md [hunk 3]
```diff
@@ -2,10 +2,15 @@
 
 ## Unreleased
 
+**Features**:
+
+- Extend GPU context with data for Unreal Engine crash reports ([#3144](https://github.com/getsentry/relay/pull/3144))
```
Comment (Dav1dde) [inline CHANGELOG.md]:
```suggestion
- Extend GPU context with data for Unreal Engine crash reports. ([#3144](https://github.com/getsentry/relay/pull/3144))
```

**Review by Dav1dde — COMMENTED** [review]
Just some tiny nits.

Thanks for looking into this!

File: CHANGELOG.md (hunk 3 above)
Comment (slonopotamus) [reply CHANGELOG.md]: Fixed

File: CHANGELOG.md (hunk 2 above)
Comment (slonopotamus) [reply CHANGELOG.md]: Done

**Review by Dav1dde — APPROVED** [review]

**Comment by Dav1dde** [comment]
Thanks for the contribution, changes should go out to SaaS today or latest tomorrow, the next Relay release will be next month!

**Comment by slonopotamus** [comment]
Fixed tests.

**Comment by slonopotamus** [comment]
That was fast, thanks.
