### PR TITLE
fix(proxy): Keep spans, profiles, and replays in proxy mode

### LINKED ISSUE #3800: Static and proxy mode should forward profiles and replays
A few months back I added this documentation because we noticed static Relays dropped replays:

> Some Sentry product features are disabled by default in Relay, either because they are still experimental or because they are not available on all plans. In static mode, these features have to be enabled manually if needed.

https://docs.sentry.io/product/relay/projects/#basic-options

We have the same problem with profiles: We filter all profiles if the feature flag is enabled, so proxy Relay cannot forward them:

https://github.com/getsentry/relay/blob/89a8dd7caaad1f126e1cacced0d73bb50fcd4f5a/relay-server/src/services/processor/profile.rs#L30-L32

This is bad for usability, and goes against the philosophy of proxy relays (which is forward everything).

Desired outcome:
* Proxy relays forward everything.
* Static relays forward everything by default.

### PR DESCRIPTION
**Pull request by jjbayer**
Fixes https://github.com/getsentry/relay/issues/3800

### CODE REVIEW

File: relay-server/src/services/processor.rs [hunk 1]
```diff
@@ -798,6 +798,9 @@ struct ProcessEnvelopeState<'a, Group> {
     /// The state of the project that this envelope belongs to.
     project_state: Arc<ProjectInfo>,
 
+    /// The config of this Relay instance.
+    config: Arc<Config>,
```
Comment (Dav1dde) [inline relay-server/src/services/processor.rs:802]: We did not have the config on the state but passed it into all the processing functions which needed it.

For example: https://github.com/getsentry/relay/blob/77ffd711852465aa1c3731b5827e7e9eec13af2d/relay-server/src/services/processor.rs#L1686-L1690

Do we want to replace all of these now as well?

File: relay-server/src/services/processor.rs [hunk 2]
```diff
@@ -863,6 +866,17 @@ impl<'a, Group> ProcessEnvelopeState<'a, Group> {
...
         self.event = Annotated::empty();
     }
+
+    /// Returns `true` for managed relays if a feature is disabled.
+    ///
+    /// Some envelope items are dropped based on a feature flag,
+    /// but we want to forward them in proxy mode.
+    fn feature_disabled_by_upstream(&self, feature: Feature) -> bool {
+        match self.config.relay_mode() {
+            RelayMode::Proxy | RelayMode::Static | RelayMode::Capture => false,
```
Comment (Dav1dde) [inline relay-server/src/services/processor.rs:876]: Is this correct for all feature flags?

If not: Possibly we make `project.has_feature()` require a `&Config` as argument?

**Review by Dav1dde — APPROVED** [review]

File: relay-server/src/services/processor.rs (hunk 1 above)
Comment (jjbayer) [reply relay-server/src/services/processor.rs:802]: Yeah good idea.

File: relay-server/src/services/processor.rs (hunk 2 above)
Comment (jjbayer) [reply relay-server/src/services/processor.rs:876]: I think this logic only makes sense for feature flags that are used to filter data. I.e. it would not make sense to assume that a feature is enabled for something like `Feature::DoExpensiveAndDangerousExperimentalStuff` in proxies. Do you think I should just rename this function to `should_filter`?

Comment (Dav1dde) [reply relay-server/src/services/processor.rs:876]: I like `should_filter`!
