### PR TITLE
fix(spans): Use `user_agent.original` for browser name

### LINKED ISSUE #3815: Normalize user agent from span `span.data`
The JS Browser SDKs will soon send the user agent string from `span.data["user_agent.original"]` in standalone INP spans (https://github.com/getsentry/sentry-javascript/issues/12689). This is done to ensure that whenever we can obtain the user agent in the SDK, it is actually sent to Sentry when sending INP spans. In several tunnelling-related scenarios (e.g. NextJS or custom tunnels), we previously lost the user agent data, causing INP spans to no longer be processed correctly. Our INP score calculation relies on the user agent so we should deliver it as often as possible.

Therefore, Relay needs to extract (and I guess parse?) the user agent string from span data, specifically `span.data["user_agent.original"]`. If this attribute is not present, we should fall back to the previously used user agent extraction method.

### PR DESCRIPTION
**Pull request by jjbayer**
Use `user_agent.original` to derive the browser name, and only use request headers if that field has not been set.

This PR also refactors span normalization, such that there is no more fake event necessary to derive user agent information or performance scores.

Fixes https://github.com/getsentry/relay/issues/3815.

### CODE REVIEW

**Review by Dav1dde — APPROVED** [review]

File: relay-server/src/services/processor/span/processing.rs [hunk 1]
```diff
@@ -528,6 +509,32 @@ fn normalize(
...
 }
 
+fn populate_ua_fields(
+    span: &mut Span,
+    request_user_agent: Option<&str>,
+    mut client_hints: ClientHints<&str>,
+) {
+    let data = span.data.value_mut().get_or_insert_with(SpanData::default);
+
+    let user_agent = data.user_agent_original.value_mut();
```
Comment (Lms24) [inline relay-server/src/services/processor/span/processing.rs:519]: just to confirm for a Relay/Rust noob: We convert `user_agent.original` to `user_agent_original` somewhere, prior to accessing it here, correct?

**Review by Lms24 — APPROVED** [review]
thanks for making the change! Looks good to me!

File: relay-server/src/services/processor/span/processing.rs (hunk 1 above)
Comment (jjbayer) [reply relay-server/src/services/processor/span/processing.rs:519]: Yes, `user_agent_original` is just the name of the field in the internal representation. In the serialized format, the field is called `user_agent.original`:

https://github.com/getsentry/relay/blob/b1e7cb85bdf4fa7f905b738d8b63fb48dd8293b2/relay-event-schema/src/protocol/span.rs#L391-L392
