### PR TITLE
ref(logs): Process logs in all non-proxy Relays

### LINKED ISSUE #4990: Relay PII scrubbing not applied in static Relay
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. In Next.js project, log a string in info level: 
```typescript
import * as Sentry from '@sentry/nextjs';
const { logger } = Sentry;
...
logger.info('filter this: John Doe');
``` 

2. In project configuration JSON file of a relay
```
{
  "slug": "my-project-slug",
  "publicKeys": [
    {
      "publicKey": "my-project-public-key",
      "isEnabled": true
    }
  ],
  "config": {
    "allowedDomains": ["*"],
    "piiConfig": {
      "version": 2,
      "rules": {
        "debug_rule": {
          "type": "pattern",
          "pattern": "(?i)john doe",
          "redaction": {
            "method": "replace",
            "text": "[Removed in relay]"
          }
        }
      },
      "applications": {
        "$string": ["debug_rule"],
        "logentry.formatted": ["debug_rule"]
      }
    }
  }
}
``` 

### Expected Result

Expecting in the Logs, I will see "filter this: [Removed in relay]"

### Actual Result

Still seeing John Doe in the logs

Image

The scrubbing on other area works

Image

But can't to get it worked for Logs, not sure is it because Logs is still in experimental phase? or I did not configure the selector for Logs correctly, many thanks in advance

### Product Area

Settings - Relay

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by Dav1dde**
The first big step at supporting inbound filters for logs.

Expansion and normalization of logs must happen in the same stage as inbound filters, since inbound filters must run at the earliest point possible to minimize unnecessary processing/traffic the normalization must also happen then.

This change enables processing of logs in all Relays except Relays running in proxy mode. Proxy mode does not have access to the necessary processing config to apply inbound filters or do full processing.

As a side effect, static and other customer managed Relays will now (correctly) apply PII rules, as they always should've been.

Tests have been improved to always use a Relay chain, size assertions are done on a trusted and untrusted Relay chain.

I also replaced the `is_from_trusted_relay` with a proper enum to not run into an issue where somewhat important information is passed around as a boolean. Adds some type-safety.

Things to be done in a follow-up:
- Actually implement inbound filters
- Split logs processing into more granular stages, normalization and scrubbing. We may want to run scrubbing only after filters to not apply unnecessary work to dropped data.

Closes: #4990
Closes: INGEST-469

### CODE REVIEW

File: relay-server/src/processing/logs/mod.rs [hunk 1]
```diff
@@ -121,21 +121,27 @@ impl processing::Processor for LogsProcessor {
...
         filter::sampled(ctx).reject(&logs)?;
 
-        self.limiter.enforce_quotas(&mut logs, ctx).await?;
+        let mut logs = process::expand(logs, ctx);
+        process::process(&mut logs, ctx);
 
-        if ctx.is_processing() {
-            let mut logs = process::expand(logs, ctx);
-            process::process(&mut logs, ctx);
+        self.limiter.enforce_quotas(&mut logs, ctx).await?;
```
Comment (loewenheim) [inline relay-server/src/processing/logs/mod.rs:142]: This means quota enforcement now happens after expansion and processing, when it was the other way around before. I assume that's intentional?

File: relay-server/src/processing/logs/process.rs [hunk 2]
```diff
@@ -101,16 +106,20 @@ fn expand_log_container(item: &Item, received_at: DateTime<Utc>) -> Result<Conta
         .into_items();
 
     for log in &mut logs {
-        let byte_size = log.value().map(relay_ourlogs::calculate_size).unwrap_or(1);
-        let header = log.header.get_or_insert_default();
-        // Unconditionally override the size of the log, before making any modifications.
+        // Calculate the received byte size and remember it as metadata, in the header.
+        // As Relay may later modify the payload later, adding attributes or removing them
+        // and in any case we want to track the originally received size.
```
Comment (loewenheim) [inline relay-server/src/processing/logs/process.rs]:
```suggestion
        // This is to keep track of the originally received size even as Relay adds or removes attributes.
```

File: relay-server/src/extractors/request_meta.rs [hunk 3]
```diff
@@ -247,7 +247,7 @@ pub struct RequestMeta<D = PartialDsn> {
     ///
     /// NOTE: This is internal-only and not exposed to Envelope headers.
     #[serde(skip)]
-    from_internal_relay: bool,
+    request_trust: Option<RequestTrust>,
```
Comment (loewenheim) [inline relay-server/src/extractors/request_meta.rs:250]: Is there an actual advantage to making this optional? AFAICT `None` has the same meaning as `Some(Untrusted)` in all cases.

File: relay-server/src/processing/logs/mod.rs (hunk 1 above)
Comment (Dav1dde) [reply relay-server/src/processing/logs/mod.rs:142]: Not yet relevant, will be relevant once we have inbound filters. We don't want to count things we're going to drop.

Also technically wrong before.

File: relay-server/src/extractors/request_meta.rs (hunk 3 above)
Comment (Dav1dde) [reply relay-server/src/extractors/request_meta.rs:250]: Yes, `copy_to` will now handle missing correctly, where before it would not. Also technically a bug that existed before and now became obvious with more typing.

**Review by loewenheim — APPROVED** [review]
